const state={data:null,filter:'all',deferredInstall:null,activeProject:null,expanded:new Set()};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const PRIORITY={Critical:0,High:1,Medium:2,Low:3};
const priorityAr={Critical:'حرج',High:'مرتفع',Medium:'متوسط',Low:'منخفض'};
const marketAr={Global:'عالمي',Rwanda:'رواندا',Ghana:'غانا',International:'دولي',Nigeria:'نيجيريا','United Kingdom':'المملكة المتحدة','United States':'الولايات المتحدة',Canada:'كندا',Belgium:'بلجيكا','Philippines / Turkey':'الفلبين / تركيا'};
const actionAr={
'Expand targeted bitumen outreach':'توسيع التواصل المستهدف مع مشتري البيتومين','Continue qualified sulfur outreach':'مواصلة التواصل المؤهل في مشروع الكبريت','Get RTDA specs and advance Yutong protected technical offer':'الحصول على مواصفات RTDA وتطوير عرض Yutong المحمي','Secure DIFFUL protection and an engaged Ghana EPC/BOQ':'تأمين حماية DIFFUL والحصول على مقاول EPC غاني وجدول الكميات','Obtain firm CIF Manila Soda Ash quote':'الحصول على عرض CIF مانيلا مؤكد','Get NFI target price and prepare buyer-ready date stock pack':'الحصول على سعر NFI المستهدف وتجهيز ملف التمور للمشتري','Get Green Focus lot/BOQ and DIFFUL protection before Sep 3':'الحصول على الحزمة وجدول الكميات من Green Focus وحماية DIFFUL','Obtain Section VII and secure Pretech commission agreement':'الحصول على القسم السابع وتأمين اتفاق عمولة Pretech','Obtain Szoneier baseline FOB/DDP UK quote and pitch retailers':'الحصول على عرض Szoneier الأساسي والتواصل مع التجزئة','Follow FlexSack quote and continue US sourcing-gap scouting':'متابعة عرض FlexSack ومواصلة البحث عن فجوات التوريد الأمريكية','Obtain UK filter manufacturer pricing and protected referral acceptance':'الحصول على أسعار الفلاتر وقبول الإحالة المحمية','Convert Canada dairy expansion into a specific equipment/procurement package':'تحويل توسعة الألبان في كندا إلى حزمة معدات ومشتريات محددة','Get Belgium cold-chain procurement route and defined refrigeration scope':'تحديد مسار المشتريات ونطاق التبريد في بلجيكا'};
const phraseMap=[
[/Waiting supplier reply/gi,'بانتظار رد المورد'],[/Waiting reply/gi,'بانتظار الرد'],[/Waiting quote/gi,'بانتظار عرض السعر'],[/Waiting firm quote/gi,'بانتظار عرض سعر مؤكد'],[/Waiting commercial confirmation/gi,'بانتظار التأكيد التجاري'],[/Waiting target buying offer/gi,'بانتظار السعر المستهدف للشراء'],[/Waiting next step/gi,'بانتظار الخطوة التالية'],[/Buyer engaged/gi,'المشتري متفاعل'],[/Supplier engaged/gi,'المورد متفاعل'],[/Strong supplier engagement/gi,'تفاعل قوي من المورد'],[/Strong supplier fit/gi,'المورد مناسب بشكل قوي'],[/Strong OEM interest/gi,'اهتمام قوي من المصنع'],[/EPC interested/gi,'المقاول مهتم'],[/Price mismatch/gi,'فجوة في السعر'],[/Severe price gap/gi,'فجوة سعرية كبيرة'],[/Resolved for current period/gi,'مغلق للفترة الحالية'],[/future window identified/gi,'تم تحديد فرصة متابعة مستقبلية'],[/Bounced/gi,'مرتد'],[/Interested/gi,'مهتم'],[/qualification advanced/gi,'تقدم في التأهيل'],[/Technical fit/gi,'ملاءمة فنية'],[/commercial protection pending/gi,'الحماية التجارية قيد الانتظار'],[/Supplier technically engaged/gi,'المورد متفاعل فنيًا'],[/Waiting lot \/ BOQ/gi,'بانتظار الحزمة وجدول الكميات'],[/Waiting supplier quotation/gi,'بانتظار عرض سعر المورد'],[/Campaign remains active/gi,'الحملة مستمرة'],[/Waiting market benchmarks/gi,'بانتظار مؤشرات السوق']
];
function b64ToBytes(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function deriveKey(pass,salt,iterations){const m=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,['decrypt'])}
async function decryptSnapshot(pass){const enc=await fetch('./data/snapshot.enc.json?v=10',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('snapshot');return r.json()});const key=await deriveKey(pass,b64ToBytes(enc.salt),enc.iterations);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(enc.iv)},key,b64ToBytes(enc.ciphertext));return JSON.parse(new TextDecoder().decode(plain))}
window.liveFetchBridge=window.liveFetchBridge||(()=>Promise.reject(new Error('Live API not configured')));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function arText(v){let s=String(v??'').trim();if(!s)return'';if(actionAr[s])return actionAr[s];phraseMap.forEach(([r,t])=>{s=s.replace(r,t)});return s}
function normalize(d){d.projects=d.projects||[];d.actions=d.actions||[];d.emails=d.emails||[];d.stats=d.stats||[];d.timeline=d.timeline||[];d.commands=d.commands||[];d.chatDestinations=d.chatDestinations||[];d.projects=d.projects.map(p=>({...p,nameAr:p.nameAr||p.name||'مشروع',marketAr:marketAr[p.market]||arText(p.market)||'—'}));return d}
function isClosed(s){return ['Done','Closed','Cancelled','مكتمل','مغلق','ملغي'].includes(String(s||''))}
function daysUntil(s){if(!s||!/\d{4}-\d{2}-\d{2}/.test(s))return null;const d=new Date(s.slice(0,10)+'T23:59:59');if(Number.isNaN(d.getTime()))return null;return Math.ceil((d-Date.now())/86400000)}
function dueText(s){const d=daysUntil(s);if(d===null)return s||'بدون موعد';if(d<0)return`متأخر ${Math.abs(d)} يوم`;if(d===0)return'اليوم';if(d===1)return'غدًا';return`بعد ${d} أيام`}
function whenText(s,short=false){if(!s)return'—';const d=new Date(s);if(Number.isNaN(d.getTime()))return s;return d.toLocaleString('ar-SA',short?{month:'short',day:'numeric'}:{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function ratioPct(v){let n=Number(String(v??0).replace(/٫/g,'.').replace('%',''));if(!Number.isFinite(n))return'0%';if(n<=1)n*=100;return`${Math.round(n)}%`}
function projectMap(){return new Map(state.data.projects.map(p=>[p.id,p]))}
function statsMap(){return new Map(state.data.stats.filter(s=>s.projectId&&s.projectId!=='TOTAL').map(s=>[s.projectId,s]))}
function totalStats(){return state.data.stats.find(s=>s.projectId==='TOTAL')||{contactedEntities:0,respondedEntities:0,engagedEntities:0,needsOurReply:0,needsAhusam:0}}
function timelineFor(id){return state.data.timeline.filter(x=>x.projectId===id).sort((a,b)=>String(a.dateTime).localeCompare(String(b.dateTime)))}
function latestTimeline(id){const a=timelineFor(id);return a.length?a[a.length-1]:null}
function openActions(){return state.data.actions.filter(a=>!isClosed(a.status)).sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999')||(PRIORITY[a.priority]??9)-(PRIORITY[b.priority]??9))}
function attentionEmails(){return state.data.emails.filter(e=>['NEEDS_OUR_REPLY','NEEDS_AHUSAM'].includes(e.replyStatus)).sort((a,b)=>(a.replyStatus==='NEEDS_AHUSAM'?-1:1)-(b.replyStatus==='NEEDS_AHUSAM'?-1:1)||String(b.lastMessageAt||'').localeCompare(String(a.lastMessageAt||'')))}
function waitingExternal(){return state.data.emails.filter(e=>e.replyStatus==='WAITING_EXTERNAL').sort((a,b)=>String(a.lastMessageAt||'').localeCompare(String(b.lastMessageAt||'')))}
function urgentActions(){return openActions().filter(a=>{const d=daysUntil(a.dueDate);return d!==null&&d<=0})}
function upcomingActions(){return openActions().filter(a=>{const d=daysUntil(a.dueDate);return d!==null&&d>0&&d<=7})}
function renderMetrics(){const t=totalStats();const need=attentionEmails().length+urgentActions().length;const metrics=[{v:need,l:'يحتاجك الآن',c:'red'},{v:t.engagedEntities||0,l:'تفاعل فعلي',c:'green'},{v:t.respondedEntities||0,l:'جهات ردت',c:'blue'},{v:t.contactedEntities||0,l:'جهات تواصلنا معها',c:'purple'}];$('#metrics').innerHTML=metrics.map(m=>`<article class="metric ${m.c}"><strong>${m.v}</strong><span>${m.l}</span></article>`).join('')}
function emailItem(e){const p=projectMap().get(e.projectId);const label=e.replyStatus==='NEEDS_AHUSAM'?'يحتاج قرارك':'يحتاج ردًا';const recent=timelineFor(e.projectId).filter(x=>x.party&&e.counterparty&&String(x.party).includes(String(e.counterparty).split('<')[0].trim())).slice(-1)[0];const detail=arText(recent?.keyPoint||recent?.summary||e.statusReason)||`وردت رسالة من ${e.counterparty||'الجهة'} وتحتاج متابعة.`;return `<article class="focus-row"><button class="row-open" type="button" data-project="${esc(e.projectId)}"><div class="row-meta"><span class="pid">${esc(e.projectId||'—')}</span><strong>${esc(p?.nameAr||e.project||'—')}</strong><span>${whenText(e.lastMessageAt,true)}</span></div><div class="row-title">${esc(detail)}</div><div class="row-sub">${esc(e.counterparty||e.lastSender||'')}</div></button><div class="row-side"><span class="flag danger">${label}</span>${e.threadLink?`<a href="${esc(e.threadLink)}" target="_blank" rel="noreferrer">البريد</a>`:''}</div></article>`}
function actionItem(a,urgent=false){const p=projectMap().get(a.projectId);return `<article class="focus-row"><button class="row-open" type="button" data-project="${esc(a.projectId)}"><div class="row-meta"><span class="pid">${esc(a.projectId)}</span><strong>${esc(p?.nameAr||a.projectId)}</strong></div><div class="row-title">${esc(arText(a.action)||'متابعة')}</div></button><div class="row-side"><span class="flag ${urgent?'danger':'warn'}">${dueText(a.dueDate)}</span></div></article>`}
function limited(sectionId,items,htmlFn,empty,limit=3){const list=$(`#${sectionId}List`),more=$(`#${sectionId}More`),expanded=state.expanded.has(sectionId),visible=expanded?items:items.slice(0,limit);list.innerHTML=visible.map(htmlFn).join('')||`<div class="empty-line">${empty}</div>`;const rest=Math.max(0,items.length-limit);if(items.length>limit){more.classList.remove('hidden');more.textContent=expanded?'عرض أقل':`عرض المزيد (${rest})`;more.onclick=()=>{expanded?state.expanded.delete(sectionId):state.expanded.add(sectionId);render()}}else more.classList.add('hidden')}
function bindProjectLinks(root=document){root.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.project)))}
function renderAttention(){const emails=attentionEmails(),acts=urgentActions();const items=[...emails.map(e=>({kind:'mail',v:e})),...acts.map(a=>({kind:'action',v:a}))];$('#attentionCount').textContent=items.length;limited('attention',items,x=>x.kind==='mail'?emailItem(x.v):actionItem(x.v,true),'لا يوجد شيء يحتاج تدخلك الآن');bindProjectLinks($('#attentionList'))}
function renderUpcoming(){const items=upcomingActions();$('#upcomingCount').textContent=items.length;limited('upcoming',items,a=>actionItem(a,false),'لا توجد متابعة قريبة');bindProjectLinks($('#upcomingList'))}
function projectScore(p){const s=statsMap().get(p.id)||{};const emailNeed=state.data.emails.filter(e=>e.projectId===p.id&&['NEEDS_OUR_REPLY','NEEDS_AHUSAM'].includes(e.replyStatus)).length;const overdue=openActions().filter(a=>a.projectId===p.id&&(daysUntil(a.dueDate)??99)<=0).length;return emailNeed*100+overdue*60+(3-(PRIORITY[p.priority]??3))*10+(s.engagedEntities||0)*2}
function projectStatsHtml(s){s=s||{};return `<div class="mini-stats"><span><b>${s.contactedEntities||0}</b> تواصل</span><span><b>${s.respondedEntities||0}</b> رد</span><span><b>${s.engagedEntities||0}</b> تفاعل</span><span><b>${ratioPct(s.replyRate)}</b> استجابة</span></div>`}
function projectRow(p){const s=statsMap().get(p.id)||{},last=latestTimeline(p.id),next=arText(last?.nextStep||p.nextAction)||'لا توجد خطوة مسجلة';return `<button class="project-row" type="button" data-project="${esc(p.id)}"><div class="project-main"><div class="project-title"><span class="pid">${esc(p.id)}</span><strong>${esc(p.nameAr)}</strong><span class="priority p-${esc(p.priority||'Medium')}">${priorityAr[p.priority]||'—'}</span></div><div class="project-next">${esc(next)}</div></div><div class="project-numbers"><span><b>${s.contactedEntities||0}</b> تواصل</span><span><b>${s.respondedEntities||0}</b> رد</span><span><b>${s.engagedEntities||0}</b> تفاعل</span><span class="arrow">‹</span></div></button>`}
function renderProjects(){let items=[...state.data.projects].sort((a,b)=>projectScore(b)-projectScore(a)||String(a.id).localeCompare(String(b.id)));if(state.filter!=='all')items=items.filter(p=>p.priority===state.filter);$('#projectsCount').textContent=items.length;limited('projects',items,projectRow,'لا توجد مشاريع',6);bindProjectLinks($('#projectsList'))}
function renderWaiting(){const items=waitingExternal();$('#waitingCount').textContent=items.length;limited('waiting',items,e=>{const p=projectMap().get(e.projectId);return `<article class="waiting-row"><button type="button" data-project="${esc(e.projectId)}"><div><span class="pid">${esc(e.projectId||'—')}</span> <strong>${esc(p?.nameAr||e.project||'—')}</strong></div><small>بانتظار رد ${esc(e.counterparty||'الطرف الآخر')}</small></button><span>${whenText(e.lastMessageAt,true)}</span></article>`},'لا توجد عناصر بانتظار الطرف الآخر');bindProjectLinks($('#waitingList'))}
function renderChats(){const canonical=['عامة','التحديثات','التخطيط','التقنية'];const map=new Map(state.data.chatDestinations.map(x=>[x.chat,x]));$('#chatBar').innerHTML=canonical.map(name=>{const ok=!!map.get(name)?.url;return `<button type="button" class="chat-btn ${ok?'':'unbound'}" data-chat="${name}">${name}</button>`}).join('');$$('[data-chat]').forEach(b=>b.addEventListener('click',()=>openChat(b.dataset.chat,'')))}
function getChat(name){return state.data.chatDestinations.find(x=>x.chat===name)}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('تم نسخ الأمر')}catch{const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();toast('تم نسخ الأمر')}}
async function openChat(name,prompt){if(prompt)await copyText(prompt);const d=getChat(name);if(d?.url){window.open(d.url,'_blank','noopener')}else toast(`أرسل رابط محادثة «${name}» مرة واحدة لربط هذا الزر`)}
function commandAllowed(c,project){const s=String(c.scope||'');return project?s.includes('Project'):s.includes('All')}
function commandPrompt(c,project){const scope=project?`${project.nameAr} (${project.id})`:'جميع المشاريع';return String(c.prompt||'').replaceAll('{SCOPE}',scope)}
function renderCommandButtons(project,container){const cmds=state.data.commands.filter(c=>String(c.active).toUpperCase()!=='FALSE'&&commandAllowed(c,project)).sort((a,b)=>(a.order||99)-(b.order||99));container.innerHTML=cmds.map(c=>`<button class="command-btn" type="button" data-command="${esc(c.id)}"><span>${esc(c.label)}</span><small>${esc(c.chat)}</small></button>`).join('')||'<div class="empty-line">لا توجد أوامر</div>';container.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>{const c=cmds.find(x=>x.id===b.dataset.command);openChat(c.chat,commandPrompt(c,project))}))}
function openCommands(project=null){state.activeProject=project?.id||null;$('#commandsTitle').textContent=project?`أوامر ${project.nameAr}`:'أوامر جميع المشاريع';renderCommandButtons(project,$('#commandsList'));$('#commandsModal').classList.remove('hidden')}
function eventLabel(ev){const t=String(ev.eventType||'').trim();if(t)return arText(t);if(ev.direction==='وارد')return'رد وارد';if(ev.direction==='صادر')return'إرسال';return'تحديث'}
function openProject(id){const p=projectMap().get(id);if(!p)return;state.activeProject=id;const s=statsMap().get(id)||{},events=timelineFor(id),last=events.length?events[events.length-1]:null;$('#projectTitle').textContent=p.nameAr;$('#projectId').textContent=p.id;$('#projectStats').innerHTML=projectStatsHtml(s);$('#projectCurrent').innerHTML=`<div><small>الوضع الآن</small><strong>${esc(arText(last?.statusAfter)||'لا توجد حالة مسجلة بعد')}</strong></div><div><small>الخطوة التالية</small><strong>${esc(arText(last?.nextStep||p.nextAction)||'—')}</strong></div>`;$('#timelineList').innerHTML=events.length?events.map(ev=>{const dir=ev.direction==='وارد'?'in':ev.direction==='صادر'?'out':'';return `<article class="timeline-event ${dir}"><div class="timeline-dot"></div><div class="timeline-body"><div class="timeline-meta"><span>${esc(eventLabel(ev))}</span><span>${whenText(ev.dateTime)}</span><span>${esc(ev.party||'')}</span></div><h4>${esc(arText(ev.summary)||'تحديث مسجل')}</h4>${ev.keyPoint?`<p><b>المهم:</b> ${esc(arText(ev.keyPoint))}</p>`:''}${ev.statusAfter?`<p><b>النتيجة:</b> ${esc(arText(ev.statusAfter))}</p>`:''}${ev.nextStep?`<p><b>التالي:</b> ${esc(arText(ev.nextStep))}</p>`:''}${ev.threadLink?`<a href="${esc(ev.threadLink)}" target="_blank" rel="noreferrer">فتح البريد</a>`:''}</div></article>`}).join(''):'<div class="empty-line">يجري بناء خط السير العربي من البريد وسجل العمليات.</div>';renderCommandButtons(p,$('#projectCommands'));$('#projectModal').classList.remove('hidden')}
function closeModals(){$$('.modal').forEach(m=>m.classList.add('hidden'))}
function render(){renderMetrics();renderChats();renderAttention();renderUpcoming();renderProjects();renderWaiting();const dt=state.data.generatedAt;$('#lastSync').textContent=dt?`آخر تحديث ${new Date(dt).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})}`:'—'}
function setStatus(text,kind){const el=$('#syncBadge');el.textContent=text;el.className='sync-status '+kind}
async function refreshData(){setStatus('● جارٍ التحديث','syncing');try{const live=await liveFetchBridge();state.data=normalize({...state.data,...live,liveApi:state.data.liveApi});render();setStatus('● متصل','live');return true}catch(e){console.warn(e);setStatus('● بيانات محفوظة','offline');return false}}
async function unlock(pass,remember){$('#lockError').textContent='';try{state.data=normalize(await decryptSnapshot(pass));if(remember)localStorage.setItem('ihq_device_key',pass);else localStorage.removeItem('ihq_device_key');$('#lockScreen').classList.add('hidden');$('#app').classList.remove('hidden');render();await refreshData()}catch(e){$('#lockError').textContent='تعذر فتح البيانات';throw e}}
function lock(){state.data=null;localStorage.removeItem('ihq_device_key');$('#accessKey').value='';$('#app').classList.add('hidden');$('#lockScreen').classList.remove('hidden')}
let toastTimer;function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
document.addEventListener('DOMContentLoaded',async()=>{$('#unlockForm').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await unlock($('#accessKey').value.trim(),$('#rememberKey').checked)}catch{}finally{b.disabled=false}});$('#refreshBtn').addEventListener('click',refreshData);$('#commandsBtn').addEventListener('click',()=>openCommands(null));$('#lockBtn').addEventListener('click',lock);$$('[data-close]').forEach(b=>b.addEventListener('click',closeModals));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;state.expanded.delete('projects');renderProjects()}));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e});$('#installBtn').addEventListener('click',async()=>{if(state.deferredInstall){state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null}else toast('من قائمة المتصفح اختر تثبيت التطبيق')});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=23').catch(console.warn);const saved=localStorage.getItem('ihq_device_key');if(saved){$('#accessKey').value=saved;try{await unlock(saved,true)}catch{localStorage.removeItem('ihq_device_key')}}});
