const state={data:null,deferredInstall:null,expanded:new Set(),filter:'all'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const PRIORITY={Critical:0,High:1,Medium:2,Low:3};
const STAGES=['اعتماد المشروع','التواصل مع الطرف الأول','التواصل مع الطرف الثاني','موافقة الطرف الأول','موافقة الطرف الثاني','حماية العمولة والنسبة','ربط الطرفين','إتمام الصفقة','استلام العمولة'];
const actionAr={'Expand targeted bitumen outreach':'توسيع التواصل المستهدف مع مشتري البيتومين','Continue qualified sulfur outreach':'مواصلة التواصل المؤهل في مشروع الكبريت'};
const hasArabic=s=>/[\u0600-\u06FF]/.test(String(s||''));
function b64ToBytes(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function deriveKey(pass,salt,iterations){const m=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,['decrypt'])}
async function decryptSnapshot(pass){const enc=await fetch('./data/snapshot.enc.json?v=10',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('snapshot');return r.json()});const key=await deriveKey(pass,b64ToBytes(enc.salt),enc.iterations);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(enc.iv)},key,b64ToBytes(enc.ciphertext));return JSON.parse(new TextDecoder().decode(plain))}
window.liveFetchBridge=window.liveFetchBridge||(()=>Promise.reject(new Error('Live API not configured')));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function normalize(d){d.projects=d.projects||[];d.actions=d.actions||[];d.emails=d.emails||[];d.stats=d.stats||[];d.timeline=d.timeline||[];d.commands=d.commands||[];d.chatDestinations=d.chatDestinations||[];d.projects=d.projects.map(p=>({...p,nameAr:p.nameAr||p.name||'مشروع'}));return d}
function projectMap(){return new Map(state.data.projects.map(p=>[p.id,p]))}
function statsMap(){return new Map(state.data.stats.filter(s=>s.projectId&&s.projectId!=='TOTAL').map(s=>[s.projectId,s]))}
function timelineFor(id){return state.data.timeline.filter(x=>x.projectId===id).sort((a,b)=>stamp(b.dateTime)-stamp(a.dateTime))}
function projectName(p){if(!p)return'مشروع';if(hasArabic(p.nameAr))return p.nameAr;const s=statsMap().get(p.id)?.project;if(hasArabic(s))return s;const t=timelineFor(p.id)[0]?.project;if(hasArabic(t))return t;return p.nameAr||p.name||p.id}
function arabicOr(s,fallback='—'){if(actionAr[s])return actionAr[s];return hasArabic(s)?s:fallback}
function stamp(s){if(!s)return 0;const d=new Date(String(s).replace(' ','T'));return Number.isNaN(d.getTime())?0:d.getTime()}
function timeParts(s){if(!s)return{date:'—',time:'—'};const raw=String(s);const d=new Date(raw.replace(' ','T'));if(Number.isNaN(d.getTime()))return{date:raw,time:'الوقت غير مسجل'};const hasTime=/\d{1,2}:\d{2}/.test(raw);return{date:d.toLocaleDateString('ar-SA',{year:'numeric',month:'short',day:'numeric'}),time:hasTime?d.toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'}):'الوقت غير مسجل'}}
function pct(v){let n=Number(String(v??0).replace(/٫/g,'.').replace('%',''));if(!Number.isFinite(n))return'0%';if(n<=1)n*=100;return Math.round(n)+'%'}
function textBlob(p){return [p.stage,p.nextAction,p.notes,...timelineFor(p.id).flatMap(e=>[e.summary,e.keyPoint,e.statusAfter,e.nextStep])].join(' ').toLowerCase()}
function progressFor(p){const explicit=String(p.stage||'').match(/(?:المرحلة\s*)?(\d)\s*\/\s*9/);if(explicit){const n=Math.max(1,Math.min(9,Number(explicit[1])));return{stage:n,percent:Math.round(n/9*100),label:STAGES[n-1]}}
 const s=statsMap().get(p.id)||{},events=timelineFor(p.id),blob=textBlob(p);let n=1;
 if(events.some(e=>['صادر','إرسال','رد منا'].includes(e.direction)||['إرسال','رد منا'].includes(e.eventType)))n=2;
 const parties=new Set(events.map(e=>String(e.party||'').trim()).filter(Boolean));if(parties.size>=2)n=Math.max(n,3);
 if((s.respondedEntities||0)>0)n=Math.max(n,4);
 if((s.engagedEntities||0)>=2||/موافقة الطرف الثاني|كلا الطرفين|both parties|buyer.*supplier|supplier.*buyer/.test(blob))n=Math.max(n,5);
 if(/تم توقيع|موقّع|وقّع.*اتفاق|حماية.*(?:مقبولة|مؤكدة|معتمدة)|signed.*(?:referral|commission|protection)|commission agreement.*signed/.test(blob))n=Math.max(n,6);
 if(/تم ربط الطرفين|تم التعريف المباشر|تم تقديم الطرفين|buyer introduced|supplier introduced|connected the parties/.test(blob))n=Math.max(n,7);
 if(/تمت الصفقة|اكتملت الصفقة|أمر شراء|purchase order|deal closed|order confirmed|won/.test(blob))n=Math.max(n,8);
 if(/استلام العمولة|تم استلام.*عمولة|commission received|commission paid/.test(blob))n=9;
 return{stage:n,percent:Math.round(n/9*100),label:STAGES[n-1]}}
function latestOperations(){return [...state.data.timeline].filter(e=>e.dateTime).sort((a,b)=>stamp(b.dateTime)-stamp(a.dateTime))}
function attention(){return state.data.emails.filter(e=>['NEEDS_OUR_REPLY','NEEDS_AHUSAM'].includes(e.replyStatus)).sort((a,b)=>stamp(b.lastMessageAt)-stamp(a.lastMessageAt))}
function renderSummary(){const sm=statsMap(),projects=state.data.projects,total=projects.length,responded=projects.filter(p=>(sm.get(p.id)?.respondedEntities||0)>0).length,engaged=projects.filter(p=>(sm.get(p.id)?.engagedEntities||0)>0).length,advanced=projects.filter(p=>progressFor(p).stage>=6).length;$('#summary').innerHTML=[['المشاريع التي بدأت',total,'blue'],['وصلها رد بشري',responded,'cyan'],['فيها تفاعل فعلي',engaged,'green'],['وصلت للحماية أو أبعد',advanced,'purple']].map(([l,v,c])=>`<article class="metric ${c}"><strong>${v}</strong><span>${l}</span></article>`).join('')}
function limited(id,items,fn,limit){const box=$('#'+id),more=$('#'+id+'More'),expanded=state.expanded.has(id),show=expanded?items:items.slice(0,limit);box.innerHTML=show.map(fn).join('')||'<div class="empty">لا توجد بيانات</div>';if(items.length>limit){more.classList.remove('hidden');more.textContent=expanded?'عرض أقل':`المزيد (${items.length-limit})`;more.onclick=()=>{expanded?state.expanded.delete(id):state.expanded.add(id);render()}}else more.classList.add('hidden')}
function renderAttention(){const pm=projectMap(),items=attention();$('#attentionCount').textContent=items.length;limited('attentionList',items,e=>{const p=pm.get(e.projectId);return `<button class="notice" data-project="${esc(e.projectId)}" type="button"><span class="notice-tag">${e.replyStatus==='NEEDS_AHUSAM'?'قرار مطلوب':'رد مطلوب'}</span><strong>${esc(projectName(p)||e.project||e.projectId)}</strong><small>${esc(arabicOr(e.statusReason,e.subject||'رسالة تحتاج متابعة'))}</small></button>`},3);bindProjects($('#attentionList'))}
function operationRow(e){const p=projectMap().get(e.projectId),t=timeParts(e.dateTime),type=e.eventType||'تحديث';return `<button class="operation" type="button" data-project="${esc(e.projectId)}" data-event="${esc(e.eventId||e.sourceId||'')}"><div class="op-time"><b>${esc(t.time)}</b><span>${esc(t.date)}</span></div><div class="op-main"><div><span class="op-type">${esc(type)}</span><strong>${esc(projectName(p)||e.project||e.projectId)}</strong></div><p>${esc(e.summary||e.keyPoint||e.subject||'تم تحديث المشروع')}</p><small>${esc(e.party||'')}</small></div><span class="chev">‹</span></button>`}
function renderOperations(){const items=latestOperations();$('#operationsCount').textContent=items.length;limited('operationsList',items,operationRow,5);$('#operationsList').querySelectorAll('[data-event]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.project,b.dataset.event)))}
function projectScore(p){const s=statsMap().get(p.id)||{},pr=progressFor(p),need=state.data.emails.filter(e=>e.projectId===p.id&&['NEEDS_OUR_REPLY','NEEDS_AHUSAM'].includes(e.replyStatus)).length;return need*1000+pr.stage*30+(PRIORITY[p.priority]===0?80:PRIORITY[p.priority]===1?50:0)+(s.engagedEntities||0)*8+stamp(timelineFor(p.id)[0]?.dateTime)/1e12}
function projectRow(p){const s=statsMap().get(p.id)||{},pr=progressFor(p),last=timelineFor(p.id)[0],t=timeParts(last?.dateTime);return `<button class="project" type="button" data-project="${esc(p.id)}"><div class="project-top"><div><span class="pid">${esc(p.id)}</span><strong>${esc(projectName(p))}</strong></div><span class="stage-label">${pr.stage}/9 · ${esc(pr.label)}</span></div><div class="progress"><i style="width:${pr.percent}%"></i></div><div class="project-bottom"><span><b>${pr.percent}%</b> إنجاز</span><span>${s.contactedEntities||0} تواصل · ${s.respondedEntities||0} رد · ${s.engagedEntities||0} تفاعل</span><span>${last?`${t.date} ${t.time}`:'لا توجد عملية'}</span></div></button>`}
function renderProjects(){let items=[...state.data.projects].sort((a,b)=>projectScore(b)-projectScore(a));if(state.filter!=='all')items=items.filter(p=>p.priority===state.filter);$('#projectsCount').textContent=items.length;limited('projectsList',items,projectRow,8);bindProjects($('#projectsList'))}
function bindProjects(root){root.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.project)))}
function stageSteps(pr){return STAGES.map((s,i)=>`<div class="step ${i+1<pr.stage?'done':i+1===pr.stage?'current':''}"><span>${i+1}</span><p>${s}</p></div>`).join('')}
function eventDetails(ev){if(!ev)return'';const t=timeParts(ev.dateTime);return `<section class="selected-event"><div class="selected-head"><span>${esc(ev.eventType||'عملية')}</span><b>${esc(t.date)} · ${esc(t.time)}</b></div><h3>${esc(ev.summary||ev.subject||'')}</h3>${ev.keyPoint?`<p><b>النقطة المهمة:</b> ${esc(ev.keyPoint)}</p>`:''}${ev.statusAfter?`<p><b>الحالة بعدها:</b> ${esc(ev.statusAfter)}</p>`:''}${ev.nextStep?`<p><b>التالي:</b> ${esc(ev.nextStep)}</p>`:''}${ev.threadLink?`<a href="${esc(ev.threadLink)}" target="_blank" rel="noreferrer">فتح البريد</a>`:''}</section>`}
function openProject(id,eventId=''){const p=projectMap().get(id);if(!p)return;const s=statsMap().get(id)||{},pr=progressFor(p),events=timelineFor(id),selected=eventId?events.find(e=>(e.eventId||e.sourceId)===eventId):events[0];$('#projectTitle').textContent=projectName(p);$('#projectId').textContent=p.id;$('#projectProgress').innerHTML=`<div class="progress-head"><strong>${pr.percent}%</strong><span>المرحلة ${pr.stage} من 9 — ${esc(pr.label)}</span></div><div class="progress big"><i style="width:${pr.percent}%"></i></div><div class="steps">${stageSteps(pr)}</div>`;$('#selectedEvent').innerHTML=eventDetails(selected);$('#projectStats').innerHTML=`<span><b>${s.contactedEntities||0}</b> جهة تم التواصل معها</span><span><b>${s.respondedEntities||0}</b> جهة ردت</span><span><b>${s.engagedEntities||0}</b> جهة متفاعلة</span><span><b>${pct(s.replyRate)}</b> معدل الرد</span>`;const next=arabicOr(p.nextAction,selected?.nextStep||'—');$('#projectCurrent').innerHTML=`<div><small>المرحلة الحالية</small><strong>المرحلة ${pr.stage}/9 — ${esc(pr.label)}</strong></div><div><small>الخطوة التالية</small><strong>${esc(next)}</strong></div>`;$('#timelineList').innerHTML=events.map(ev=>{const t=timeParts(ev.dateTime);return `<article class="timeline-event"><div class="timeline-date"><b>${esc(t.time)}</b><span>${esc(t.date)}</span></div><div><div class="timeline-meta"><span>${esc(ev.eventType||'تحديث')}</span><span>${esc(ev.party||'')}</span></div><p>${esc(ev.summary||ev.subject||'')}</p>${ev.keyPoint?`<small>${esc(ev.keyPoint)}</small>`:''}</div></article>`}).join('')||'<div class="empty">لا يوجد سجل بعد</div>';renderProjectCommands(p);$('#projectModal').classList.remove('hidden')}
function getChat(name){return state.data.chatDestinations.find(x=>x.chat===name)}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('تم نسخ الأمر')}catch{toast('تعذر النسخ')}}
async function openChat(name,prompt=''){if(prompt)await copyText(prompt);const d=getChat(name);if(d?.url)window.open(d.url,'_blank','noopener');else toast(`رابط محادثة ${name} غير مسجل`)}
function renderChats(){const names=['عامة','التحديثات','التخطيط','التقنية'];$('#chatBar').innerHTML=names.map(n=>`<button type="button" data-chat="${n}" class="chat-btn ${getChat(n)?.url?'':'unbound'}">${n}</button>`).join('');$$('[data-chat]').forEach(b=>b.addEventListener('click',()=>openChat(b.dataset.chat)))}
function commandAllowed(c,p){const s=String(c.scope||'');return p?s.includes('Project'):s.includes('All')}
function commandPrompt(c,p){return String(c.prompt||'').replaceAll('{SCOPE}',p?`${projectName(p)} (${p.id})`:'جميع المشاريع')}
function renderProjectCommands(p){const cmds=state.data.commands.filter(c=>String(c.active).toUpperCase()!=='FALSE'&&commandAllowed(c,p)).slice(0,6);$('#projectCommands').innerHTML=cmds.map(c=>`<button type="button" data-pcmd="${esc(c.id)}"><span>${esc(c.label)}</span><small>${esc(c.chat)}</small></button>`).join('');$$('[data-pcmd]').forEach(b=>b.addEventListener('click',()=>{const c=cmds.find(x=>x.id===b.dataset.pcmd);openChat(c.chat,commandPrompt(c,p))}))}
function openCommands(){const cmds=state.data.commands.filter(c=>String(c.active).toUpperCase()!=='FALSE'&&commandAllowed(c,null));$('#commandsList').innerHTML=cmds.map(c=>`<button type="button" data-cmd="${esc(c.id)}"><span>${esc(c.label)}</span><small>${esc(c.chat)}</small></button>`).join('');$$('[data-cmd]').forEach(b=>b.addEventListener('click',()=>{const c=cmds.find(x=>x.id===b.dataset.cmd);openChat(c.chat,commandPrompt(c,null))}));$('#commandsModal').classList.remove('hidden')}
function render(){renderSummary();renderChats();renderAttention();renderOperations();renderProjects();$('#lastSync').textContent=state.data.generatedAt?new Date(state.data.generatedAt).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'}):'—'}
function setStatus(t,k){const e=$('#syncBadge');e.textContent=t;e.className='sync-status '+k}
async function refreshData(){setStatus('● تحديث','syncing');try{const live=await liveFetchBridge();state.data=normalize({...state.data,...live,liveApi:state.data.liveApi});render();setStatus('● مباشر','live');return true}catch(e){console.warn(e);setStatus('● محفوظ','offline');return false}}
async function unlock(pass,remember){$('#lockError').textContent='';try{state.data=normalize(await decryptSnapshot(pass));remember?localStorage.setItem('ihq_device_key',pass):localStorage.removeItem('ihq_device_key');$('#lockScreen').classList.add('hidden');$('#app').classList.remove('hidden');render();await refreshData()}catch(e){$('#lockError').textContent='تعذر فتح البيانات';throw e}}
function lock(){state.data=null;localStorage.removeItem('ihq_device_key');$('#app').classList.add('hidden');$('#lockScreen').classList.remove('hidden')}
function closeModals(){$$('.modal').forEach(m=>m.classList.add('hidden'))}
let tt;function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(tt);tt=setTimeout(()=>e.classList.remove('show'),2200)}
document.addEventListener('DOMContentLoaded',async()=>{$('#unlockForm').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await unlock($('#accessKey').value.trim(),$('#rememberKey').checked)}catch{}finally{b.disabled=false}});$('#refreshBtn').onclick=refreshData;$('#commandsBtn').onclick=openCommands;$('#lockBtn').onclick=lock;$$('[data-close]').forEach(b=>b.onclick=closeModals);$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModals()}));$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderProjects()});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e});$('#installBtn').onclick=async()=>{if(state.deferredInstall){state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null}else toast('من قائمة المتصفح اختر تثبيت التطبيق')};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=25').catch(console.warn);const saved=localStorage.getItem('ihq_device_key');if(saved){$('#accessKey').value=saved;try{await unlock(saved,true)}catch{localStorage.removeItem('ihq_device_key')}}});