/** Investment HQ — read-only relay. Gmail intelligence is handled by Investment Mail Engine. */
const DASHBOARD_URL_='https://darbpath.com/investment-hq/';
function doGet(){return HtmlService.createHtmlOutput('<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><base target="_top"></head><body style="margin:0;background:#000;color:#fff;font-family:ui-monospace,Consolas,monospace"><main style="min-height:100vh;display:grid;place-items:center"><a href="'+DASHBOARD_URL_+'" target="_top" style="color:#55ff88;border:1px solid #55ff88;padding:12px 16px;text-decoration:none">[ فتح لوحة الاستثمار ]</a></main></body></html>').setTitle('Investment HQ')}
function doPost(e){const mode=String(e&&e.parameter&&e.parameter.mode||'');return relayOutput_(mode==='relay'?buildPayload_(e):{ok:false,error:'Invalid relay mode'},e)}
function relayOutput_(payload,e){const nonce=String(e&&e.parameter&&e.parameter.nonce||'').replace(/[^0-9a-f]/gi,'').slice(0,64);const gz=Utilities.gzip(Utilities.newBlob(JSON.stringify({payload:payload}),'application/json'));const encoded=Utilities.base64EncodeWebSafe(gz.getBytes()).replace(/=+$/,'');const dest=DASHBOARD_URL_+'#ihq='+encoded+'&n='+nonce;const html='<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><base target="_top"></head><body style="margin:0;background:#000;color:#fff;font-family:ui-monospace,Consolas,monospace"><main style="min-height:100vh;display:grid;place-items:center;padding:20px"><section style="width:min(92vw,390px);border:1px solid #333;padding:22px"><div style="color:#55ff88;margin-bottom:14px">● اكتملت المزامنة</div><a href="'+escapeHtml_(dest)+'" target="_top" rel="noreferrer" style="display:block;border:1px solid #55ff88;color:#55ff88;padding:13px;text-align:center;text-decoration:none">[ العودة للوحة ]</a></section></main></body></html>';return HtmlService.createHtmlOutput(html).setTitle('Investment HQ')}
function buildPayload_(e){try{const props=PropertiesService.getScriptProperties();const expected=String(props.getProperty('ACCESS_TOKEN')||'');const supplied=String(e&&e.parameter&&e.parameter.token||'');if(!expected||!safeEqual_(supplied,expected))return{ok:false,error:'Unauthorized'};const id=String(props.getProperty('MASTER_SHEET_ID')||'');if(!id)return{ok:false,error:'MASTER_SHEET_ID is not configured'};const ss=SpreadsheetApp.openById(id);return{ok:true,generatedAt:new Date().toISOString(),projects:normalizeProjects_(readTable_(ss,'Projects')),actions:normalizeActions_(readTable_(ss,'Actions')),emails:normalizeEmailTracker_(readTable_(ss,'Email Tracker')),stats:normalizeStats_(readTable_(ss,'Project Stats')),timeline:normalizeTimeline_(readTable_(ss,'Project Timeline')),commands:normalizeCommands_(readTable_(ss,'Chat Commands')),chatDestinations:normalizeChatDestinations_(readTable_(ss,'Chat Destinations'))}}catch(err){return{ok:false,error:String(err&&err.message||err)}}}
function readTable_(ss,name){const sh=ss.getSheetByName(name);if(!sh)return[];const v=sh.getDataRange().getDisplayValues();if(v.length<2)return[];const h=v[0].map(x=>String(x||'').trim());return v.slice(1).filter(r=>r.some(x=>String(x||'').trim()!=='')).map(r=>{const o={};h.forEach((k,i)=>{if(k)o[k]=r[i]||''});return o})}
function normalizeProjects_(rows){return rows.map(r=>({id:r['Project ID']||'',name:r['Project']||'',nameAr:r['Arabic Name']||r['Project']||'',category:r['Category']||'',market:r['Market']||'',status:r['Status']||'',priority:r['Priority']||'',stage:r['Stage']||'',deadline:r['Deadline']||'',score:r['Score']||'',nextAction:r['Next Action']||'',lastUpdate:r['Last Update']||'',gmailLabel:r['Gmail Label']||'',projectFolder:r['Project Folder']||'',primaryFile:r['Primary File']||''}))}
function normalizeActions_(rows){return rows.map(r=>({id:r['Action ID']||'',projectId:r['Project ID']||'',action:r['Action']||'',priority:r['Priority']||'',status:r['Status']||'',dueDate:r['Due Date']||'',relatedCompany:r['Related Company']||'',owner:r['Owner']||''}))}
function normalizeEmailTracker_(rows){return rows.map(r=>({threadId:r['Thread ID']||'',projectId:r['Project ID']||'',project:r['Project']||'',gmailLabel:r['Gmail Label']||'',subject:r['Subject']||'',counterparty:r['Counterparty']||'',lastDirection:r['Last Direction']||'',lastSender:r['Last Sender']||'',lastMessageAt:r['Last Message At']||'',replyStatus:r['Reply Status']||'',replied:r['Replied']||'',threadLink:r['Thread Link']||'',statusReason:r['Status Reason']||'',checkedAt:r['Checked At']||''}))}
function normalizeStats_(rows){return rows.map(r=>({projectId:r['Project ID']||'',project:r['Project']||'',contactedEntities:num_(r['Contacted Entities']),respondedEntities:num_(r['Responded Entities']),humanReplies:num_(r['Human Replies']),engagedEntities:num_(r['Engaged Entities']),positiveEngagements:num_(r['Positive Engagements']),replyRate:r['Reply Rate']||'0',engagementRate:r['Engagement Rate']||'0',waitingExternal:num_(r['Waiting External']),needsOurReply:num_(r['Needs Our Reply']),needsAhusam:num_(r['Needs Ahusam']),bounced:num_(r['Bounced']),lastInbound:r['Last Inbound']||'',lastOutbound:r['Last Outbound']||'',checkedAt:r['Checked At']||''}))}
function normalizeTimeline_(rows){return rows.map(r=>({eventId:r['معرف الحدث']||'',projectId:r['معرف المشروع']||'',project:r['المشروع']||'',dateTime:r['التاريخ والوقت']||'',eventType:r['نوع الحدث']||'',direction:r['الاتجاه']||'',party:r['الجهة']||'',subject:r['العنوان']||'',summary:r['الملخص العربي']||'',keyPoint:r['الطلب أو النقطة المهمة']||'',statusAfter:r['الحالة بعد الحدث']||'',nextStep:r['الخطوة التالية']||'',threadLink:r['رابط البريد']||'',sourceId:r['معرف المصدر']||''}))}
function normalizeCommands_(rows){return rows.map(r=>({id:r['Command ID']||'',label:r['Label']||'',chat:r['Destination Chat']||'',scope:r['Scope']||'',prompt:r['Prompt Template']||'',active:r['Active']||'',order:num_(r['Order']),notes:r['Notes']||''}))}
function normalizeChatDestinations_(rows){return rows.map(r=>({chat:r['المحادثة']||'',url:r['الرابط']||'',active:r['مفعلة']||'',order:num_(r['الترتيب']),description:r['الوصف']||''}))}
function num_(v){const n=Number(String(v||'0').replace(/,/g,'').replace(/٫/g,'.').trim());return Number.isFinite(n)?n:0}
function escapeHtml_(v){return String(v).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function safeEqual_(a,b){if(a.length!==b.length)return false;let out=0;for(let i=0;i<a.length;i++)out|=a.charCodeAt(i)^b.charCodeAt(i);return out===0}
